// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"
	"time"

	desc "github.com/utrack/clay/integration/no_panic_in_response_marshaler_for_timestamp/pb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func (i *StringsImplementation) Echo(ctx context.Context, req *desc.EchoReq) (*desc.EchoResp, error) {
	return &desc.EchoResp{Stdtime: timestamppb.New(time.Date(2018, 1, 1, 1, 1, 1, 1, time.UTC))}, nil
}
