// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings/strings.proto

package strings

import (
	"context"

	"github.com/pkg/errors"
	desc "github.com/utrack/clay/integration/gogo_enums/pb/strings"
)

func (i *StringsImplementation) ToLower(ctx context.Context, req *desc.String) (*desc.String, error) {
	return nil, errors.New("not implemented")
}
