// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sum.proto

package sumpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SumRequest is a request for Summator service.
type SumRequest struct {
	// A is the number we're adding to. Can't be zero for the sake of example.
	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	// B is the number we're adding.
	B                    *BStruct `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sum_92bd275642b92a04, []int{0}
}
func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (dst *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(dst, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *SumRequest) GetB() *BStruct {
	if m != nil {
		return m.B
	}
	return nil
}

type SumResponse struct {
	Sum                  int64    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sum_92bd275642b92a04, []int{1}
}
func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (dst *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(dst, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SumResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BStruct struct {
	B                    int64    `protobuf:"varint,1,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BStruct) Reset()         { *m = BStruct{} }
func (m *BStruct) String() string { return proto.CompactTextString(m) }
func (*BStruct) ProtoMessage()    {}
func (*BStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_sum_92bd275642b92a04, []int{2}
}
func (m *BStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BStruct.Unmarshal(m, b)
}
func (m *BStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BStruct.Marshal(b, m, deterministic)
}
func (dst *BStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BStruct.Merge(dst, src)
}
func (m *BStruct) XXX_Size() int {
	return xxx_messageInfo_BStruct.Size(m)
}
func (m *BStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BStruct proto.InternalMessageInfo

func (m *BStruct) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "sumpb.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "sumpb.SumResponse")
	proto.RegisterType((*BStruct)(nil), "sumpb.BStruct")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SummatorClient is the client API for Summator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SummatorClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type summatorClient struct {
	cc *grpc.ClientConn
}

func NewSummatorClient(cc *grpc.ClientConn) SummatorClient {
	return &summatorClient{cc}
}

func (c *summatorClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/sumpb.Summator/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummatorServer is the server API for Summator service.
type SummatorServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
}

func RegisterSummatorServer(s *grpc.Server, srv SummatorServer) {
	s.RegisterService(&_Summator_serviceDesc, srv)
}

func _Summator_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummatorServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sumpb.Summator/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummatorServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Summator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sumpb.Summator",
	HandlerType: (*SummatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Summator_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sum.proto",
}

func init() { proto.RegisterFile("sum.proto", fileDescriptor_sum_92bd275642b92a04) }

var fileDescriptor_sum_92bd275642b92a04 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x8b, 0xc2, 0x30,
	0x10, 0x85, 0x37, 0x5b, 0xba, 0xdd, 0x4e, 0x45, 0x74, 0x10, 0x2c, 0xe2, 0xa1, 0xe4, 0xd4, 0x53,
	0x0e, 0x15, 0x41, 0x3c, 0xf6, 0x27, 0x24, 0x37, 0x6f, 0x8d, 0xe4, 0x18, 0x53, 0x93, 0xcc, 0xff,
	0x97, 0xa6, 0x15, 0xbd, 0xcd, 0x0c, 0xf3, 0xde, 0xf7, 0x1e, 0x94, 0x81, 0xac, 0x18, 0xbd, 0x8b,
	0x0e, 0xf3, 0x40, 0x76, 0xd4, 0xfc, 0x02, 0xa0, 0xc8, 0x4a, 0xf3, 0x24, 0x13, 0x22, 0xae, 0x80,
	0x0d, 0x35, 0x6b, 0x58, 0x9b, 0x49, 0x36, 0xe0, 0x11, 0x98, 0xae, 0x7f, 0x1b, 0xd6, 0x56, 0xdd,
	0x5a, 0xa4, 0x77, 0xd1, 0xab, 0xe8, 0xe9, 0x1e, 0x25, 0xd3, 0xfc, 0x0c, 0x55, 0x52, 0x86, 0xd1,
	0x3d, 0x82, 0xc1, 0x0d, 0x64, 0x81, 0xec, 0x22, 0x9e, 0x46, 0xdc, 0x41, 0x6e, 0xbc, 0x77, 0x3e,
	0x59, 0x94, 0x72, 0x5e, 0xf8, 0x1e, 0x8a, 0xc5, 0x64, 0xa2, 0xe9, 0x37, 0x4d, 0x77, 0x57, 0xf8,
	0x57, 0x64, 0xed, 0x10, 0x9d, 0x47, 0x01, 0x99, 0x22, 0x8b, 0xdb, 0x85, 0xfa, 0x49, 0x78, 0xc0,
	0xef, 0xd3, 0x8c, 0xe6, 0x3f, 0x7d, 0x71, 0x9b, 0xeb, 0xe8, 0xbf, 0x54, 0xee, 0xf4, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0xa0, 0xe1, 0xa2, 0xe9, 0x00, 0x00, 0x00,
}
