// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"
	"strings"

	desc "github.com/utrack/clay/integration/additional_bindings/pb"
	transport "github.com/utrack/clay/v2/transport"
)

type StringsImplementation struct{}

func NewStrings() *StringsImplementation {
	return &StringsImplementation{}
}

func (i *StringsImplementation) ToUpper(ctx context.Context, req *desc.String) (*desc.String, error) {
	resp := &desc.String{Str: strings.ToUpper(req.GetStr())}
	return resp, nil
}

func (i *StringsImplementation) ToLower(ctx context.Context, req *desc.String) (*desc.String, error) {
	resp := &desc.String{Str: strings.ToLower(req.GetStr())}
	return resp, nil
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *StringsImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewStringsServiceDesc(i)
}
