// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings/strings.proto

package strings

import (
	"context"

	empty "github.com/gogo/protobuf/types"
	"github.com/pkg/errors"
)

func (i *Implementation) WithoutDesc(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, errors.New("not implemented")
}
