// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings/strings.proto

package strings

import (
	"context"

	empty "github.com/gogo/protobuf/types"
	"github.com/pkg/errors"
	desc "github.com/utrack/clay/integration/google_empty/pb/strings"
)

func (i *Implementation) EmptyResponse(ctx context.Context, req *desc.EmptyRequest) (*empty.Empty, error) {
	return nil, errors.New("not implemented")
}
