// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"

	desc "github.com/utrack/clay/integration/response_vs_response_body/pb"
)

func (i *StringsImplementation) Echo2(ctx context.Context, req *desc.ListTypes) (*desc.ListTypes, error) {
	return req, nil
}
