// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	desc "github.com/utrack/clay/integration/response_vs_response_body/pb"
	"github.com/utrack/clay/v2/transport"
)

type StringsImplementation struct{}

// NewStrings create new StringsImplementation
func NewStrings() *StringsImplementation {
	return &StringsImplementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *StringsImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewStringsServiceDesc(i)
}
