// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"

	desc "github.com/utrack/clay/integration/impl_exists/pb"
	"strings"
)

func (i *StringsImplementation) ToUpper(ctx context.Context, req *desc.String) (*desc.String, error) {
	return &desc.String{Str: strings.ToUpper(req.Str)}, nil
}