// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	desc "github.com/utrack/clay/integration/impl_exists/pb"
	"github.com/utrack/clay/v3/transport"
)

type StringsImplementation struct {
	desc.UnimplementedStringsServer
}

func NewStrings() *StringsImplementation {
	return &StringsImplementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *StringsImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewStringsServiceDesc(i)
}
