// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pb/sum.proto

package sum

import (
	"context"

	"github.com/pkg/errors"
	desc "github.com/utrack/clay/doc/example/pb"
)

func (i *SummatorImplementation) Sum(ctx context.Context, req *desc.SumRequest) (*desc.SumResponse, error) {
	if req.GetA() == 0 {
		return nil, errors.New("a is zero")
	}

	if req.GetB().B == 65536 {
		panic(errors.New("we've got a problem; the panic is planned to happen"))
	}

	sum := req.GetA() + req.GetB().B
	return &desc.SumResponse{
		Sum: sum,
	}, nil
}
