// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pb/sum.proto

package sum

import (
	desc "github.com/utrack/clay/doc/example/pb"
	"github.com/utrack/clay/v2/transport"
)

type SummatorImplementation struct {
	desc.UnimplementedSummatorServer
}

// NewSummator create new SummatorImplementation
func NewSummator() *SummatorImplementation {
	return &SummatorImplementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *SummatorImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewSummatorServiceDesc(i)
}
