// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"

	desc "github.com/utrack/clay/integration/binding_with_different_types_post/pb"
)

func (i *StringsImplementation) Echo(ctx context.Context, req *desc.Types) (*desc.Types, error) {
	return req, nil
}
