// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"
	"strings"

	desc "github.com/utrack/clay/integration/binding_with_repeated_field/pb"
)

func (i *StringsImplementation) ToUpper(ctx context.Context, req *desc.String) (rsp *desc.String, err error) {
	rsp = &desc.String{}
	for _, str := range req.Str {
		rsp.Str = append(rsp.Str, strings.ToUpper(str))
	}
	return
}
